// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseExecution.Infrastructure.Persistence;

#nullable disable

namespace WarehouseExecution.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324103000_AddLocations")]
    partial class AddLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseExecution.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("JobNumber")
                        .IsUnique();

                    b.HasIndex("ToLocationId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("WarehouseExecution.Domain.Entities.JobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("JobId", "StepNumber")
                        .IsUnique();

                    b.HasIndex("ToLocationId");

                    b.ToTable("JobSteps", (string)null);
                });

            modelBuilder.Entity("WarehouseExecution.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0b57672-6ec3-45d6-bf6b-5f6d07ba2ac1"),
                            Code = "A-01",
                            CreatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Inbound Buffer A-01",
                            UpdatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a6de81a2-827a-4ef8-ab80-69a304a4c613"),
                            Code = "A-02",
                            CreatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Inbound Buffer A-02",
                            UpdatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4b250f3b-6537-4ca8-872f-fb702db9d712"),
                            Code = "B-01",
                            CreatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Storage Lane B-01",
                            UpdatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77bfa0d1-517e-48ec-8846-5646041ebf66"),
                            Code = "B-02",
                            CreatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Storage Lane B-02",
                            UpdatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("97ccb9f8-525f-43b8-80d7-04727a2adfe4"),
                            Code = "P-01",
                            CreatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Packing Station P-01",
                            UpdatedAtUtc = new DateTime(2026, 3, 24, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WarehouseExecution.Infrastructure.Persistence.JobNumberCounter", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("JobNumberCounters", (string)null);
                });

            modelBuilder.Entity("WarehouseExecution.Domain.Entities.Job", b =>
                {
                    b.HasOne("WarehouseExecution.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseExecution.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseExecution.Domain.Entities.JobStep", b =>
                {
                    b.HasOne("WarehouseExecution.Domain.Entities.Job", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseExecution.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseExecution.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WarehouseExecution.Domain.Entities.Job", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
